export const FETCH_USER = 'vtn/user/FETCH_USER';
export const FETCH_USER_SUCCESS = 'vtn/user/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'vtn/user/FETCH_USER_FAILURE';

export const LOGIN = 'vtn/user/LOGIN';
export const LOGIN_SUCCESS = 'vtn/user/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'vtn/user/LOGIN_FAILURE';

export const LOGOUT = 'vtn/user/LOGOUT';
export const LOGOUT_SUCCESS = 'vtn/user/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'vtn/user/LOGOUT_FAILURE';

export const REFRESH_TOKEN = 'vtn/user/REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'vtn/user/REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'vtn/user/REFRESH_TOKEN_FAILURE';

export const FETCH_USER_APPLICATIONS = 'vtn/user/FETCH_USER_APPLICATIONS';
export const FETCH_USER_APPLICATIONS_SUCCESS =
  'vtn/user/FETCH_USER_APPLICATIONS_SUCCESS';
export const FETCH_USER_APPLICATIONS_FAILURE =
  'vtn/user/FETCH_USER_APPLICATIONS_FAILURE';

export const RESET_USER_PASSWORD = 'vtn/user/RESET_USER_PASSWORD';
export const RESET_USER_PASSWORD_SUCCESS =
  'vtn/user/RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_FAILURE =
  'vtn/user/RESET_USER_PASSWORD_FAILURE';

export const UPDATE_CURRENT_USER_PROFILE =
  'vtn/user/UPDATE_CURRENT_USER_PROFILE';
export const UPDATE_CURRENT_USER_PROFILE_SUCCESS =
  'vtn/user/UPDATE_CURRENT_USER_PROFILE_SUCCESS';
export const UPDATE_CURRENT_USER_PROFILE_FAILURE =
  'vtn/user/UPDATE_CURRENT_USER_PROFILE_FAILURE';
