export const REQUEST_OAUTH_GRANT = 'REQUEST_OAUTH_GRANT';
export const REQUEST_OAUTH_GRANT_IMPLICIT = 'REQUEST_OAUTH_GRANT_IMPLICIT';
export const OAUTH_GRANT_FLOW_FAILED = 'OAUTH_GRANT_FLOW_FAILED';
export const OAUTH_GRANT_FLOW_SUCCESS = 'OAUTH_GRANT_FLOW_SUCCESS';
export const SET_SESSION_TOKEN = 'vtn/user/SET_SESSION_TOKEN';
export const SET_OAUTH_TOKEN = 'vtn/user/SET_OAUTH_TOKEN';
export const CHECK_AUTH_NO_TOKEN = 'vtn/user/CHECK_AUTH_NO_TOKEN';
