export default {
  rangeInput: {
    display: 'flex',
    justifyContent: 'left',
    flexWrap: 'wrap',
    width: 400,
  },
  renderTrack: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 170,
    marginTop: 5,
  },
  renderThum: {
    height: 15,
    width: 15,
    borderRadius: '50%',
    backgroundColor: '#4285F4',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // boxShadow: '0px 2px 6px #AAA',
  },
  trackLine: {
    height: 3,
    width: '100%',
    borderRadius: 4,
    alignSelf: 'center',
  },
  valueMin: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 30,
    marginRight: 15,
    boxShadow: '0 1px 1px #ddd',
  },
  valueMax: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 30,
    marginLeft: 15,
    boxShadow: '0 1px 1px #ddd',
  },
}
