name: CXGO SCAN
'on':
  schedule:
      - cron: '0 0 */60 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - if: github.event_name == 'push'
        name: Extract Branch Name
        run: 'echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV'
      - if: github.event_name == 'pull_request'
        name: Extract Branch Name
        run: 'echo "BRANCH=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV'
      - name: Install cxgo-cli npm package
        run: npm install -g @cxgo/cli
      - name: Scan project sources with cxgo-cli
        run: >-
          cxgo-cli scan:start --project-id=33
          --api-url=https://api.checkmarx.net  --scan-tag=${GITHUB_SHA}
          --source-folder=${GITHUB_WORKSPACE} --branch-name=${BRANCH}
        env:
          CXGO_TOKEN: '${{ secrets.CXGO_TOKEN }}'
